package com.dsa.summarizer.service;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class TranscriptService {
    
    private static final Logger logger = LoggerFactory.getLogger(TranscriptService.class);
    private final Gson gson = new Gson();
    
    @Autowired
    private CommentMiningService commentMiningService;
    
    // Filler words to remove
    private static final String[] FILLERS = {
        "um", "uh", "like", "you know", "so", "basically", "actually", 
        "literally", "kind of", "sort of", "i mean", "right"
    };
    
    /**
     * Fetches transcript from YouTube video with comprehensive fallback logic
     */
    public String fetchTranscript(String videoId) throws Exception {
        logger.info("=== STARTING TRANSCRIPT FETCH FOR VIDEO: {} ===", videoId);
        
        // FALLBACK 1: Try manual captions
        logger.info("FALLBACK 1: Attempting to fetch manual captions");
        try {
            String manualTranscript = fetchManualCaptions(videoId);
            if (manualTranscript != null && !manualTranscript.trim().isEmpty()) {
                logger.info("✓ SUCCESS: Manual captions found. Length: {} characters", manualTranscript.length());
                return cleanTranscript(manualTranscript);
            }
            logger.warn("✗ Manual captions not available or empty");
        } catch (Exception e) {
            logger.warn("✗ Failed to fetch manual captions: {}", e.getMessage());
        }
        
        // FALLBACK 2: Try auto-generated captions (ASR)
        logger.info("FALLBACK 2: Attempting to fetch auto-generated captions (ASR)");
        try {
            String asrTranscript = fetchAutoGeneratedCaptions(videoId);
            if (asrTranscript != null && !asrTranscript.trim().isEmpty()) {
                logger.info("✓ SUCCESS: Auto-generated captions found. Length: {} characters", asrTranscript.length());
                return cleanTranscript(asrTranscript);
            }
            logger.warn("✗ Auto-generated captions not available or empty");
        } catch (Exception e) {
            logger.warn("✗ Failed to fetch auto-generated captions: {}", e.getMessage());
        }
        
        // FALLBACK 3: Build pseudo-transcript from comments and metadata
        logger.info("FALLBACK 3: Building pseudo-transcript from comments and metadata");
        try {
            String pseudoTranscript = commentMiningService.buildPseudoTranscript(videoId);
            if (pseudoTranscript != null && !pseudoTranscript.trim().isEmpty()) {
                logger.info("✓ SUCCESS: Pseudo-transcript built from comments. Length: {} characters", 
                    pseudoTranscript.length());
                // Don't clean pseudo-transcript as aggressively - preserve structure
                return pseudoTranscript;
            }
            logger.error("✗ Pseudo-transcript is empty or null");
        } catch (Exception e) {
            logger.error("✗ Failed to build pseudo-transcript: {}", e.getMessage(), e);
        }
        
        // ALL FALLBACKS FAILED
        logger.error("=== ALL TRANSCRIPT FALLBACKS FAILED FOR VIDEO: {} ===", videoId);
        throw new RuntimeException(
            "Unable to obtain transcript for this video. Tried: " +
            "(1) Manual captions, (2) Auto-generated captions, (3) Comments mining. " +
            "The video may not have captions, audio, or meaningful comments."
        );
    }
    
    /**
     * Attempts to fetch manual captions
     */
    private String fetchManualCaptions(String videoId) throws Exception {
        logger.debug("Fetching manual captions for video: {}", videoId);
        
        String videoPageUrl = "https://www.youtube.com/watch?v=" + videoId;
        String videoPage = fetchUrl(videoPageUrl);
        
        String captionTrackUrl = extractCaptionTrackUrl(videoPage, videoId, false);
        
        if (captionTrackUrl == null) {
            return null;
        }
        
        String transcriptXml = fetchUrl(captionTrackUrl);
        return parseTranscriptXml(transcriptXml);
    }
    
    /**
     * Attempts to fetch auto-generated captions (ASR)
     */
    private String fetchAutoGeneratedCaptions(String videoId) throws Exception {
        logger.debug("Fetching auto-generated captions for video: {}", videoId);
        
        String videoPageUrl = "https://www.youtube.com/watch?v=" + videoId;
        String videoPage = fetchUrl(videoPageUrl);
        
        String captionTrackUrl = extractCaptionTrackUrl(videoPage, videoId, true);
        
        if (captionTrackUrl == null) {
            return null;
        }
        
        String transcriptXml = fetchUrl(captionTrackUrl);
        return parseTranscriptXml(transcriptXml);
    }
    
    /**
     * Extracts caption track URL from video page HTML
     */
    private String extractCaptionTrackUrl(String html, String videoId, boolean autoGenerated) {
        Pattern pattern = Pattern.compile("\"captionTracks\":\\[(.*?)\\]");
        Matcher matcher = pattern.matcher(html);
        
        if (matcher.find()) {
            String captionTracksJson = "[" + matcher.group(1) + "]";
            try {
                JsonArray tracks = JsonParser.parseString(captionTracksJson).getAsJsonArray();
                
                for (int i = 0; i < tracks.size(); i++) {
                    JsonObject track = tracks.get(i).getAsJsonObject();
                    
                    // Check if it's the right kind (manual or auto-generated)
                    boolean isAsr = track.has("kind") && 
                        "asr".equals(track.get("kind").getAsString());
                    
                    if (autoGenerated == isAsr && track.has("baseUrl")) {
                        String baseUrl = track.get("baseUrl").getAsString();
                        baseUrl = baseUrl.replace("\\u0026", "&");
                        
                        logger.debug("Found {} caption track: {}", 
                            autoGenerated ? "auto-generated" : "manual", baseUrl);
                        return baseUrl;
                    }
                }
            } catch (Exception e) {
                logger.error("Failed to parse caption tracks", e);
            }
        }
        
        return null;
    }
    
    /**
     * Parses transcript XML and extracts text
     */
    private String parseTranscriptXml(String xml) {
        StringBuilder transcript = new StringBuilder();
        
        Pattern pattern = Pattern.compile("<text[^>]*>([^<]+)</text>");
        Matcher matcher = pattern.matcher(xml);
        
        int count = 0;
        while (matcher.find()) {
            String text = matcher.group(1);
            text = decodeHtmlEntities(text);
            transcript.append(text).append(" ");
            count++;
        }
        
        logger.debug("Parsed {} text segments from transcript XML", count);
        return transcript.toString().trim();
    }
    
    /**
     * Cleans transcript by removing fillers, timestamps, and noise
     */
    public String cleanTranscript(String transcript) {
        logger.debug("Cleaning transcript. Original length: {} characters", transcript.length());
        
        if (transcript == null || transcript.trim().isEmpty()) {
            return "";
        }
        
        String cleaned = transcript.toLowerCase();
        
        // Remove filler words
        for (String filler : FILLERS) {
            cleaned = cleaned.replaceAll("\\b" + Pattern.quote(filler) + "\\b", "");
        }
        
        // Remove multiple spaces
        cleaned = cleaned.replaceAll("\\s+", " ");
        
        // Remove [Music], [Applause], etc.
        cleaned = cleaned.replaceAll("\\[[^\\]]+\\]", "");
        
        // Remove timestamps
        cleaned = cleaned.replaceAll("\\d{1,2}:\\d{2}(:\\d{2})?", "");
        
        // Remove special characters
        cleaned = cleaned.replaceAll("[\\x00-\\x1F\\x7F]", "");
        
        // Capitalize sentences
        cleaned = capitalizeSentences(cleaned);
        
        logger.debug("Transcript cleaned. Final length: {} characters", cleaned.length());
        return cleaned.trim();
    }
    
    /**
     * Capitalizes first letter of sentences
     */
    private String capitalizeSentences(String text) {
        if (text == null || text.isEmpty()) {
            return text;
        }
        
        StringBuilder result = new StringBuilder(text.length());
        boolean capitalizeNext = true;
        
        for (char c : text.toCharArray()) {
            if (capitalizeNext && Character.isLetter(c)) {
                result.append(Character.toUpperCase(c));
                capitalizeNext = false;
            } else {
                result.append(c);
                if (c == '.' || c == '!' || c == '?') {
                    capitalizeNext = true;
                }
            }
        }
        
        return result.toString();
    }
    
    /**
     * Decodes HTML entities
     */
    private String decodeHtmlEntities(String text) {
        if (text == null) {
            return "";
        }
        
        return text.replace("&amp;", "&")
                   .replace("&lt;", "<")
                   .replace("&gt;", ">")
                   .replace("&quot;", "\"")
                   .replace("&#39;", "'")
                   .replace("&apos;", "'")
                   .replace("&nbsp;", " ")
                   .replace("&#x27;", "'")
                   .replace("&#x2F;", "/");
    }
    
    /**
     * Fetches content from URL
     */
    private String fetchUrl(String urlString) throws Exception {
        logger.debug("Fetching URL: {}", urlString);
        
        URL url = new URL(urlString);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");
        conn.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36");
        conn.setRequestProperty("Accept-Language", "en-US,en;q=0.9");
        conn.setConnectTimeout(10000);
        conn.setReadTimeout(10000);
        
        int responseCode = conn.getResponseCode();
        if (responseCode != 200) {
            throw new RuntimeException("Failed to fetch URL. HTTP response code: " + responseCode);
        }
        
        BufferedReader in = new BufferedReader(
            new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8)
        );
        String inputLine;
        StringBuilder content = new StringBuilder();
        
        while ((inputLine = in.readLine()) != null) {
            content.append(inputLine);
        }
        
        in.close();
        conn.disconnect();
        
        return content.toString();
    }
}